# Generated by Django 5.0.6 on 2024-05-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='deliverystatus',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='orderstatus',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='receive',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
