# Generated by Django 5.0.6 on 2024-05-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
