# Generated by Django 5.0.6 on 2024-05-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_customeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
