# Generated by Django 5.0.6 on 2024-05-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_customeraddress_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='delivary_boy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
