# Generated by Django 5.0.6 on 2024-05-25 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_cartitem_id'),
        ('restaurants', '0003_remove_restaurant_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurants.restaurant'),
            preserve_default=False,
        ),
    ]
