# Generated by Django 5.0.6 on 2024-05-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_order_product_order_delivery_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('just_placed', 'just_placed'), ('on_process', 'on_process'), ('on_delivery', 'on_delivery'), ('delivered', 'delivered')], default='just_placed', max_length=20),
        ),
    ]
