# Generated by Django 5.0.6 on 2024-05-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_order_products_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
