# Generated by Django 5.0.6 on 2024-06-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_remove_order_products_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
