# Generated by Django 5.0 on 2024-05-10 16:17

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(default='Name', max_length=200)),
                ('first_name', models.CharField(default='First Name', max_length=200)),
                ('last_name', models.CharField(default='Last Name', max_length=200)),
                ('profile_image', models.ImageField(blank=True, default=User.models.default_profile_image, null=True, upload_to='profile_images/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('rider', 'Rider'), ('admin', 'Admin')], default='customer', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
