# Generated by Django 5.0.6 on 2024-05-15 15:07

import User.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default=User.models.default_profile_image, null=True, upload_to='profile_images/')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('contactNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('NidNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('vehicleType', models.CharField(blank=True, max_length=20, null=True)),
                ('drivingLicense', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
